version: '3.8'

services:
  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"  # External : port in container
      - "5679:5679"  # Debugging port
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/investment_support_system
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5679", "-m", "app",  "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # React port 3000
    networks:
      - app-network
    depends_on:
      - flask-backend

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"  # MongoDB port 27017
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  app-network: